version: '3.5'

services:
  image-manipulation-service:
    build: .
    image:  midianok/image-manipulation-service:latest
    restart: always
    environment:
      ASPNETCORE_URLS: "http://*:5001"
    ports:
      - "127.0.0.1:5001:5001"